services:
  sample-authorization-server:
    container_name: sample-authorization-server
    build:
      context: ./
      dockerfile: Dockerfile
    image: sample-authorization-server:latest
    ports:
      - 9000:9000
    networks:
      - auth-network
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/test
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      APP_ALLOWED-ORIGINS: http://localhost:4200
      APP_REDIRECT-URIS: http://localhost:4200
      APP_SCOPES: openid,api.read,api.write
      APP_ACCESS-TOKEN-DURATION: 5 # in minutes
      APP_REFRESH-TOKEN-DURATION: 8 # in hours
  sample-proxy-server:
    container_name: sample-proxy-server
    build:
      context: ../sample-proxy-server
      dockerfile: Dockerfile
    image: sample-proxy-server:latest
    ports:
      - 8082:8082
    networks:
      - auth-network
    depends_on:
      - sample-authorization-server
    environment:
      APP_AUTH-SERVER-URL: http://sample-authorization-server:9000
      APP_ALLOWED-ORIGINS: http://localhost:4200
      APP_CLIENT-ID: oidc-client
      APP_CLIENT-SECRET: oidc
    deploy:
        restart_policy:
          condition: on-failure
          delay: 5s
          max_attempts: 3
          window: 120s
  sample-resource-server:
    container_name: sample-resource-server
    build:
      context: ../sample-resource-server
      dockerfile: Dockerfile
    image: sample-resource-server:latest
    ports:
      - 8081:8081
    networks:
      - auth-network
    depends_on:
      - postgres
      - sample-authorization-server
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/test
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      APP_AUTH-SERVER-URL: http://sample-authorization-server:9000
      APP_ALLOWED-ORIGINS: http://localhost:4200
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_OPAQUE_INTROSPECTION-CLIENT-ID: oidc-client
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_OPAQUE_INTROSPECTION-CLIENT-SECRET: oidc
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_OPAQUE_INTROSPECTION-URI: http://sample-authorization-server:9000/oauth2/introspect
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test
    ports:
      - "5432:5432"
    networks:
      - auth-network
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
networks:
  auth-network:
